name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *" # Runs daily at 18:00 UTC
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3

      # This action generates the SVG file
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        with:
          # Replace 'YOUR-USERNAME' with your GitHub username
          USERNAME: Utu-A
          # To change the color/look, search the action's repo for more options
          MAX_COLUMN: 100
          
      # This step commits the newly generated SVG file back to the repository
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated 3D contrib" || echo "No changes to commit"
          git push
